Updated release workflow

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -1,7 +1,7 @@
 name: Create Release
 
 env:
-  PACKAGE-FILENAME: 'bcgov-citz-imb-kc-css-api'
+  PACKAGE-FILENAME: 'bcgov-citz-imb-sso-css-api'
   CHANGELOG: '' # Leave empty.
 
 on:
@@ -13,6 +13,38 @@ on:
         required: true
 
 jobs:
+  check_version_change:
+    runs-on: ubuntu-latest
+    steps:
+      # Checkout code
+      - name: Checkout repository
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0 # Fetch all history for all tags and branches
+      
+      # Fetch all tags
+      - name: Fetch tags
+        run: git fetch --tags
+
+      # Get latest tag name
+      - name: Get latest tag
+        id: latest_tag
+        run: echo "::set-output name=TAG::$(git describe --tags `git rev-list --tags --max-count=1`)"
+
+      # Get version from package.json
+      - name: Get package version
+        id: package_version
+        run: echo "::set-output name=VERSION::$(node -p "require('./package.json').version")"
+
+      # Compare versions and fail if they match
+      - name: Compare versions and fail if necessary
+        run: |
+          if [ "v${{ steps.package_version.outputs.VERSION }}" == "${{ steps.latest_tag.outputs.TAG }}" ]; then
+            echo "Version in package.json (${{ steps.package_version.outputs.VERSION }}) matches the latest tag (${{ steps.latest_tag.outputs.TAG }})."
+            echo "You must update the version with 'npm run bump' before a release can be made."
+            exit 1
+          fi
+          
   create_release:
     runs-on: ubuntu-latest
     steps:
@@ -40,7 +72,14 @@ jobs:
         id: package_version
         run: echo "::set-output name=VERSION::$(node -p "require('./package.json').version")"
 
-      # Create new release
+      # Publish package to NPM
+      - name: Publish to npm
+        uses: JS-DevTools/npm-publish@v3
+        with:
+          token: ${{ secrets.NPM_TOKEN }}
+          access: public
+
+      # Create new release in GitHub
       - name: Create GitHub Release
         id: create_release
         uses: softprops/action-gh-release@v1
